modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}"
license="${mod_license}"

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/LotrExtendedTeam/Extended-Patches"

[[mods]] #mandatory
modId="extended_patches"
version="${mod_version}"
displayName="${mod_name}"
# A URL to query for updates for this mod. See the JSON update specification https://docs.minecraftforge.net/en/latest/misc/updatechecker/
updateJSONURL="https://raw.githubusercontent.com/LotrExtendedTeam/Extended-Patches/main/ExtendedPatchVersions.json"
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://github.com/LotrExtendedTeam/Extended-Patches"
# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="examplemod.png" #optional
#credits="" #optional
authors="LotrExtendedTeam"
description='''${mod_description}'''

[[dependencies.extended_patches]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"


[[dependencies.extended_patches]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.extended_patches]]
modId="lotrextended"
mandatory=true
versionRange="[1.10.2]"
ordering="AFTER"
side="BOTH"
